remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Wolfenstein 3d Remake
description: Trabajo practico final grupal Taller I (75.42) Fiuba
